# Generated by Django 2.1.1 on 2018-10-04 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendlog',
            name='response',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Response'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='send_at',
            field=models.DateTimeField(help_text='Use ISO 8601 format'),
        ),
    ]
