# Generated by Django 2.1.2 on 2018-10-25 19:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20181004_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='emoji',
            name='emoji',
            field=models.CharField(blank=True, help_text='The actual emoji 💩', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='send_at',
            field=models.DateTimeField(help_text='Use ISO 8601 format. All times are UTC.'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='sent',
            field=models.BooleanField(default=False, help_text='Does not indicate success/failure, only whether an attempt was made'),
        ),
    ]
