# Generated by Django 2.1.2 on 2018-10-25 20:15

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20181025_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='expiration',
            field=models.DateTimeField(default=api.models.get_expiration),
        ),
    ]
